---

deploy:
  provider: releases
  token: $GITHUB_TOKEN
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  file_glob: true
  file: bin/release/*
  skip_cleanup: true
  draft: true
  on:
    tags: false
    all_branches: true
