---

before_deploy:
  - git config --local user.email "builds@travis-ci.com"
  - git config --local user.name "Travis CI"
  - export TRAVIS_TAG="${APP_VERSION}"
  - git tag $TRAVIS_TAG
  - ls -al bin/release
