---

before_install:
  - export PORTAPPS_DIR=${PORTAPPS_DIR:-${TRAVIS_BUILD_DIR}/../portapps}
  - source ${PORTAPPS_DIR}/.travis/prepare.sh
  - bash ${PORTAPPS_DIR}/.travis/java.sh
  - bash ${PORTAPPS_DIR}/.travis/ant.sh
  - bash ${PORTAPPS_DIR}/.travis/nodejs.sh
  - bash ${PORTAPPS_DIR}/.travis/go.sh
