---

before_install:
  - export PORTAPPS_DIR=${PORTAPPS_DIR:-${TRAVIS_BUILD_DIR}/../portapps}
  - export PORTAPPS_VERSION=${PORTAPPS_VERSION:-master}
  - git clone --branch ${PORTAPPS_VERSION} https://github.com/portapps/portapps ${PORTAPPS_DIR}
  - source ${PORTAPPS_DIR}/.travis/prepare.sh
  - bash ${PORTAPPS_DIR}/.travis/java.sh
  - bash ${PORTAPPS_DIR}/.travis/ant.sh
  - bash ${PORTAPPS_DIR}/.travis/nodejs.sh
  - bash ${PORTAPPS_DIR}/.travis/go.sh
